### PR TITLE
Milestone 2 - Responsive Web Design

### PR DESCRIPTION
**Pull request by sneufa**
This is a clone of the cached version of a version of thenextweb.com

- Using media queries and following best practices of responsive web design.
- Using responsive images for differenet device sizes.
- Designing layout using flex.

### CODE REVIEW

**Review by arslanbisharat — CHANGES_REQUESTED** [review]
# Changes Requested 💀 

Thank you for submitting this Pull Request. You have done a great job so far! 👏 

There is room for improvement in the code. I would recommend following these suggestions to make your project outstanding.

- [ ] Please remove !important from your CSS code. Always try to keep your code [clean](https://www.w3schools.com/html/html5_syntax.asp). 
- [ ] Please use the same color for the text as given in the design. 
Capture


When you are done with these changes request another review.  🧻 

**Best,
Arslan Bisharat**
In case of any question please reach out to me at @arslanbisharat on slack 📞

**Comment by sneufa** [comment]
> # Changes Requested 
> Thank you for submitting this Pull Request. You have done a great job so far! 
> 
> There is room for improvement in the code. I would recommend following these suggestions to make your project outstanding.
> 
> * [ ]  Please remove !important from your CSS code. Always try to keep your code [clean](https://www.w3schools.com/html/html5_syntax.asp).
> * [ ]  Please use the same color for the text as given in the design.
> 
> Capture
> 
> When you are done with these changes request another review. 
> 
> **Best, Arslan Bisharat**
> In case of any question please reach out to me at @arslanbisharat on slack

- Removed all the !important tags.
- Fixed the color issues.

**Review by mikenath223 — CHANGES_REQUESTED** [review]
### Hello Team 👋

**You've done pretty well here fixing issues raised in the previous review. 👌**

However, let's make a couple of changes.

- [x] In the Latest Deals section on the tablet screen there should be three articles per row, not just two as seen in yours.

| Original  | Yours |
| ------------- | ------------- |
| ice_screenshot_20210304-082325 |  ice_screenshot_20210304-082346 |


### **STATUS: CHANGES REQUESTED** 👷‍♂️

Kindly fix these issues and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

**HAPPY CODING 🎉💻🎉**

**Michgolden Ukeje (CR)**

**Comment by sneufa** [comment]
Actually, there aren't two cards on the tablet screen, you're mistaken. There are as many as there should be.

**Review by whiz25 — CHANGES_REQUESTED** [review]
## Changes Required 🙏🏿 
Nice work making the requested changes. However, we need to make some changes to the `Latest deals` section as suggested.
I understand what you did with the empty columns but the original page doesn't have empty columns. This is a clone of the original page so everything has to look close to that as possible.
- [ ] Fill the empty columns with content when the app is on tablet mode.



### Martin Afani

**Review by MuriloRoque — APPROVED** [review]
## Status: Approved :green_circle: 

### Hello @sneufa :wave: 

### Thank you for making all of the requested changes. Your project is approved :clap: :clap: :clap: 

### You may merge, good luck with your next projects :rocket: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[Twitter Follow](https://twitter.com/MuriloRoquePai1)

**Pull request merged**
